### ISSUE TITLE
Make the test suite compile with GHC 9.0

### ISSUE THREAD

**Issue by RyanGlScott** [DanielSchuessler/th-expand-syns#21]
As noted in https://github.com/DanielSchuessler/th-expand-syns/issues/20#issuecomment-797520810, the test suite currently doesn't compile with GHC 9.0:

```
[1 of 3] Compiling Util             ( testing/Util.hs, interpreted )

testing/Util.hs:19:24: error:
    • Couldn't match type: flag0 -> TyVarBndr flag0
                     with: TyVarBndr Specificity
      Expected: [TyVarBndr Specificity]
        Actual: [flag0 -> TyVarBndr flag0]
    • In the first argument of ‘forallT’, namely
        ‘((PlainTV . mkName) `fmap` xs)’
      In the expression: forallT ((PlainTV . mkName) `fmap` xs)
      In an equation for ‘forallT'’:
          forallT' xs = forallT ((PlainTV . mkName) `fmap` xs)
   |
19 | forallT' xs = forallT ((PlainTV . mkName) `fmap` xs)
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I've sketched out a fix for this in https://github.com/DanielSchuessler/th-expand-syns/pull/19#issuecomment-779806474. This issue serves as a reminder to implement it.

**Comment by RyanGlScott** [comment]
Fixed in 9aae9448e3a2a4216d4ab6613debd1ec7717f230.
